name: Build Emscripten and Publish Pages
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pages branch
      uses: actions/checkout@v3
      ref: pages

    - name: Sync
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: master
        target_branch: pages
        github_token: ${{ github.token }}
    
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v11
      with:
        # Make sure to set a version number!
        version: 3.1.24
        # This is the name of the cache folder.
        # The cache folder will be placed in the build directory,
        #  so make sure it doesn't conflict with anything!
        actions-cache-folder: 'emsdk-cache'
    
    - name: Build
      run: ./build_emcc.sh
      
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add docs
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "CI: Automated build push" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
