name: Publish

on:
  workflow_dispatch: 
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev
    
    - name: Configure CMake
      run: cmake . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: make

    - name: Pack into DEB
      run: cpack -G DEB
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sdlminesweeper.deb
        asset_name: sdlminesweeper-linux64.deb
        # temp hardcode tag for debugging
        # tag: ${{ github.ref }}
        tag: "1.1.0"
        overwrite: true
        body: "Release binaries."
