name: Publish

on:
  workflow_dispatch: 
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish Linux
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev
    
    - name: Configure CMake
      run: cmake . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: make -j

    - name: Pack deb and rpm
      run: cpack -G "DEB;RPM"
      
    - name: Upload DEB
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sdlminesweeper.deb
        asset_name: sdlminesweeper-linux64.deb
        # temp hardcode tag for debugging
        # tag: ${{ github.ref }}
        tag: "1.1.0"
      
    - name: Upload RPM
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sdlminesweeper.rpm
        asset_name: sdlminesweeper-linux64.rpm
        # temp hardcode tag for debugging
        # tag: ${{ github.ref }}
        tag: "1.1.0"
