name: Win Test Build

on:
  workflow-dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

  steps:
  - name: Test Software
    run: |
      mingw32-make --version
      cmake --version
