name: Win Test Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-SDL2_ttf
          mingw-w64-x86_64-SDL2_mixer

      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -G Ninja . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: ninja

      - name: CPack
        run: cpack

