name: Windows Environment Info

on: workflow_dispatch

jobs:
  build-win64:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Dump
      run: |
        choco install mingw
        ls C:/
