name: Windows Environment Info

on: workflow_dispatch

jobs:
  build-win64:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Dump
      run: |
        ls C:/
        gcc --version
        g++ --version
        $env:PATH
